import type { Metadata } from "next";
import "../../styles/globals.css";
import Header from "@/components/header/header";
import Navbar from "@/components/navbar/navbar";

// 메타데이터 설정
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <div className="min-h-screen flex flex-col items-center relative">
      {/* Header */}
      <div className="w-full h-16 bg-mainGreen z-20 fixed top-0 left-0">
        <Header />
      </div>

      {/* Main Content */}
      <main className="px-4 py-24 w-400px mx-auto relative z-10 overflow-x-auto">
        {children}
      </main>

      {/* Navbar */}
      <div className="w-full bg-mainGreen fixed bottom-0 left-0 z-20">
        <Navbar />
      </div>
    </div>
  );
};

export default RootLayout;
